### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by GmAccount** [mindreframer/docker-stuff#1]
I want to use [Sourcegraph](https://sourcegraph.com) for docker-stuff code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mindreframer/docker-stuff. (It should only take 30 seconds.)

Thank you!

**Comment by mindreframer** [comment]
@GmAccount not sure if this is some promotion thing for sourcegraph, but I have just activated it. Hope the need is a real one

**Comment by mindreframer** [comment]
the build has failed, but i wont spend much time on that, sorry

https://sourcegraph.com/github.com/mindreframer/docker-stuff/.builds/2305734
